[2025-03-23T12:37:49.205+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-23T12:37:49.219+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_yf_scraper.run_reddit manual__2025-03-23T03:10:55.075296+00:00 [queued]>
[2025-03-23T12:37:49.223+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_yf_scraper.run_reddit manual__2025-03-23T03:10:55.075296+00:00 [queued]>
[2025-03-23T12:37:49.223+0800] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-23T12:37:49.230+0800] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): run_reddit> on 2025-03-23 03:10:55.075296+00:00
[2025-03-23T12:37:49.233+0800] {standard_task_runner.py:72} INFO - Started process 2626 to run task
[2025-03-23T12:37:49.237+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_yf_scraper', 'run_reddit', 'manual__2025-03-23T03:10:55.075296+00:00', '--job-id', '140', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/var/folders/xg/h9xj0trn3dxds251bj2q6hf80000gn/T/tmpg0fd9l5a']
[2025-03-23T12:37:49.238+0800] {standard_task_runner.py:105} INFO - Job 140: Subtask run_reddit
[2025-03-23T12:37:49.268+0800] {task_command.py:467} INFO - Running <TaskInstance: reddit_yf_scraper.run_reddit manual__2025-03-23T03:10:55.075296+00:00 [running]> on host ervins-air-2
[2025-03-23T12:37:49.305+0800] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='reddit_yf_scraper' AIRFLOW_CTX_TASK_ID='run_reddit' AIRFLOW_CTX_EXECUTION_DATE='2025-03-23T03:10:55.075296+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-23T03:10:55.075296+00:00'
[2025-03-23T12:37:49.306+0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-23T12:37:49.307+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-23T12:37:49.307+0800] {logging_mixin.py:190} INFO - Current task name:run_reddit state:running start_date:2025-03-23 04:37:49.219345+00:00
[2025-03-23T12:37:49.307+0800] {logging_mixin.py:190} INFO - Dag name:reddit_yf_scraper and current dag run status:running
[2025-03-23T12:37:49.307+0800] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-23T12:37:50.130+0800] {patcher.py:346} INFO - patching driver executable /Users/ervinyeoh/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2025-03-23T12:38:55.354+0800] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/dag.py", line 46, in run_reddit
    run_reddit_scraper(tickers)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/reddit_scraper.py", line 21, in run_reddit_scraper
    driver = uc.Chrome()
             ^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:60107
from unknown error: unable to discover open pages
Stacktrace:
0   undetected_chromedriver             0x00000001047d0568 undetected_chromedriver + 6088040
1   undetected_chromedriver             0x00000001047c817a undetected_chromedriver + 6054266
2   undetected_chromedriver             0x0000000104267540 undetected_chromedriver + 415040
3   undetected_chromedriver             0x00000001042a6f92 undetected_chromedriver + 675730
4   undetected_chromedriver             0x000000010429c5de undetected_chromedriver + 632286
5   undetected_chromedriver             0x00000001042edbdc undetected_chromedriver + 965596
6   undetected_chromedriver             0x00000001042ed0c6 undetected_chromedriver + 962758
7   undetected_chromedriver             0x00000001042df1c3 undetected_chromedriver + 905667
8   undetected_chromedriver             0x00000001042ab05a undetected_chromedriver + 692314
9   undetected_chromedriver             0x00000001042ac1b1 undetected_chromedriver + 696753
10  undetected_chromedriver             0x000000010478fc90 undetected_chromedriver + 5823632
11  undetected_chromedriver             0x0000000104793b44 undetected_chromedriver + 5839684
12  undetected_chromedriver             0x000000010476ae86 undetected_chromedriver + 5672582
13  undetected_chromedriver             0x000000010479453b undetected_chromedriver + 5842235
14  undetected_chromedriver             0x0000000104759824 undetected_chromedriver + 5601316
15  undetected_chromedriver             0x00000001047b6618 undetected_chromedriver + 5981720
16  undetected_chromedriver             0x00000001047b67df undetected_chromedriver + 5982175
17  undetected_chromedriver             0x00000001047c7d58 undetected_chromedriver + 6053208
18  libsystem_pthread.dylib             0x00007ff80802d259 _pthread_start + 125
19  libsystem_pthread.dylib             0x00007ff808028c7b thread_start + 15

[2025-03-23T12:38:55.380+0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-23T12:38:55.380+0800] {logging_mixin.py:190} INFO - Task start:2025-03-23 04:37:49.219345+00:00 end:2025-03-23 04:38:55.379404+00:00 duration:66.160059
[2025-03-23T12:38:55.381+0800] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): run_reddit> dag:<DAG: reddit_yf_scraper> dagrun:<DagRun reddit_yf_scraper @ 2025-03-23 03:10:55.075296+00:00: manual__2025-03-23T03:10:55.075296+00:00, state:running, queued_at: 2025-03-23 03:10:55.104993+00:00. externally triggered: True>
[2025-03-23T12:38:55.381+0800] {logging_mixin.py:190} INFO - Failure caused by Message: session not created: cannot connect to chrome at 127.0.0.1:60107
from unknown error: unable to discover open pages
Stacktrace:
0   undetected_chromedriver             0x00000001047d0568 undetected_chromedriver + 6088040
1   undetected_chromedriver             0x00000001047c817a undetected_chromedriver + 6054266
2   undetected_chromedriver             0x0000000104267540 undetected_chromedriver + 415040
3   undetected_chromedriver             0x00000001042a6f92 undetected_chromedriver + 675730
4   undetected_chromedriver             0x000000010429c5de undetected_chromedriver + 632286
5   undetected_chromedriver             0x00000001042edbdc undetected_chromedriver + 965596
6   undetected_chromedriver             0x00000001042ed0c6 undetected_chromedriver + 962758
7   undetected_chromedriver             0x00000001042df1c3 undetected_chromedriver + 905667
8   undetected_chromedriver             0x00000001042ab05a undetected_chromedriver + 692314
9   undetected_chromedriver             0x00000001042ac1b1 undetected_chromedriver + 696753
10  undetected_chromedriver             0x000000010478fc90 undetected_chromedriver + 5823632
11  undetected_chromedriver             0x0000000104793b44 undetected_chromedriver + 5839684
12  undetected_chromedriver             0x000000010476ae86 undetected_chromedriver + 5672582
13  undetected_chromedriver             0x000000010479453b undetected_chromedriver + 5842235
14  undetected_chromedriver             0x0000000104759824 undetected_chromedriver + 5601316
15  undetected_chromedriver             0x00000001047b6618 undetected_chromedriver + 5981720
16  undetected_chromedriver             0x00000001047b67df undetected_chromedriver + 5982175
17  undetected_chromedriver             0x00000001047c7d58 undetected_chromedriver + 6053208
18  libsystem_pthread.dylib             0x00007ff80802d259 _pthread_start + 125
19  libsystem_pthread.dylib             0x00007ff808028c7b thread_start + 15
[2025-03-23T12:38:55.381+0800] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=reddit_yf_scraper, task_id=run_reddit, run_id=manual__2025-03-23T03:10:55.075296+00:00, execution_date=20250323T031055, start_date=20250323T043749, end_date=20250323T043855
[2025-03-23T12:38:55.392+0800] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-23T12:38:55.393+0800] {standard_task_runner.py:124} ERROR - Failed to execute job 140 for task run_reddit (Message: session not created: cannot connect to chrome at 127.0.0.1:60107
from unknown error: unable to discover open pages
Stacktrace:
0   undetected_chromedriver             0x00000001047d0568 undetected_chromedriver + 6088040
1   undetected_chromedriver             0x00000001047c817a undetected_chromedriver + 6054266
2   undetected_chromedriver             0x0000000104267540 undetected_chromedriver + 415040
3   undetected_chromedriver             0x00000001042a6f92 undetected_chromedriver + 675730
4   undetected_chromedriver             0x000000010429c5de undetected_chromedriver + 632286
5   undetected_chromedriver             0x00000001042edbdc undetected_chromedriver + 965596
6   undetected_chromedriver             0x00000001042ed0c6 undetected_chromedriver + 962758
7   undetected_chromedriver             0x00000001042df1c3 undetected_chromedriver + 905667
8   undetected_chromedriver             0x00000001042ab05a undetected_chromedriver + 692314
9   undetected_chromedriver             0x00000001042ac1b1 undetected_chromedriver + 696753
10  undetected_chromedriver             0x000000010478fc90 undetected_chromedriver + 5823632
11  undetected_chromedriver             0x0000000104793b44 undetected_chromedriver + 5839684
12  undetected_chromedriver             0x000000010476ae86 undetected_chromedriver + 5672582
13  undetected_chromedriver             0x000000010479453b undetected_chromedriver + 5842235
14  undetected_chromedriver             0x0000000104759824 undetected_chromedriver + 5601316
15  undetected_chromedriver             0x00000001047b6618 undetected_chromedriver + 5981720
16  undetected_chromedriver             0x00000001047b67df undetected_chromedriver + 5982175
17  undetected_chromedriver             0x00000001047c7d58 undetected_chromedriver + 6053208
18  libsystem_pthread.dylib             0x00007ff80802d259 _pthread_start + 125
19  libsystem_pthread.dylib             0x00007ff808028c7b thread_start + 15
; 2626)
Traceback (most recent call last):
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/dag.py", line 46, in run_reddit
    run_reddit_scraper(tickers)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/reddit_scraper.py", line 21, in run_reddit_scraper
    driver = uc.Chrome()
             ^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 250, in __init__
    self.start_session(capabilities)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 342, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:60107
from unknown error: unable to discover open pages
Stacktrace:
0   undetected_chromedriver             0x00000001047d0568 undetected_chromedriver + 6088040
1   undetected_chromedriver             0x00000001047c817a undetected_chromedriver + 6054266
2   undetected_chromedriver             0x0000000104267540 undetected_chromedriver + 415040
3   undetected_chromedriver             0x00000001042a6f92 undetected_chromedriver + 675730
4   undetected_chromedriver             0x000000010429c5de undetected_chromedriver + 632286
5   undetected_chromedriver             0x00000001042edbdc undetected_chromedriver + 965596
6   undetected_chromedriver             0x00000001042ed0c6 undetected_chromedriver + 962758
7   undetected_chromedriver             0x00000001042df1c3 undetected_chromedriver + 905667
8   undetected_chromedriver             0x00000001042ab05a undetected_chromedriver + 692314
9   undetected_chromedriver             0x00000001042ac1b1 undetected_chromedriver + 696753
10  undetected_chromedriver             0x000000010478fc90 undetected_chromedriver + 5823632
11  undetected_chromedriver             0x0000000104793b44 undetected_chromedriver + 5839684
12  undetected_chromedriver             0x000000010476ae86 undetected_chromedriver + 5672582
13  undetected_chromedriver             0x000000010479453b undetected_chromedriver + 5842235
14  undetected_chromedriver             0x0000000104759824 undetected_chromedriver + 5601316
15  undetected_chromedriver             0x00000001047b6618 undetected_chromedriver + 5981720
16  undetected_chromedriver             0x00000001047b67df undetected_chromedriver + 5982175
17  undetected_chromedriver             0x00000001047c7d58 undetected_chromedriver + 6053208
18  libsystem_pthread.dylib             0x00007ff80802d259 _pthread_start + 125
19  libsystem_pthread.dylib             0x00007ff808028c7b thread_start + 15

[2025-03-23T12:38:55.433+0800] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-23T12:38:55.452+0800] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-23T12:38:55.454+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
