[2025-04-19T11:35:32.393+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-19T11:35:32.400+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_yf_scraper.fetch_yesterday_data manual__2025-04-19T03:28:54.867003+00:00 [queued]>
[2025-04-19T11:35:32.404+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_yf_scraper.fetch_yesterday_data manual__2025-04-19T03:28:54.867003+00:00 [queued]>
[2025-04-19T11:35:32.405+0800] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-19T11:35:32.410+0800] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): fetch_yesterday_data> on 2025-04-19 03:28:54.867003+00:00
[2025-04-19T11:35:32.414+0800] {standard_task_runner.py:72} INFO - Started process 15334 to run task
[2025-04-19T11:35:32.418+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_yf_scraper', 'fetch_yesterday_data', 'manual__2025-04-19T03:28:54.867003+00:00', '--job-id', '680', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/var/folders/2f/rw5w89ss6nl38qvq2cxrh29w0000gn/T/tmp93ijho_5']
[2025-04-19T11:35:32.419+0800] {standard_task_runner.py:105} INFO - Job 680: Subtask fetch_yesterday_data
[2025-04-19T11:35:32.440+0800] {task_command.py:467} INFO - Running <TaskInstance: reddit_yf_scraper.fetch_yesterday_data manual__2025-04-19T03:28:54.867003+00:00 [running]> on host yueyaos-macbook-pro.local
[2025-04-19T11:35:32.468+0800] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='reddit_yf_scraper' AIRFLOW_CTX_TASK_ID='fetch_yesterday_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-19T03:28:54.867003+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-19T03:28:54.867003+00:00'
[2025-04-19T11:35:32.468+0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-19T11:35:32.469+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-19T11:35:32.469+0800] {logging_mixin.py:190} INFO - Current task name:fetch_yesterday_data state:running start_date:2025-04-19 03:35:32.401098+00:00
[2025-04-19T11:35:32.469+0800] {logging_mixin.py:190} INFO - Dag name:reddit_yf_scraper and current dag run status:running
[2025-04-19T11:35:32.469+0800] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-19T11:35:33.553+0800] {logging_mixin.py:190} WARNING - /Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/google/cloud/bigquery/table.py:1933 UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
[2025-04-19T11:35:34.069+0800] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/airflow/dags/dag.py", line 425, in fetch_yesterday_data
    df.to_pickle(PICKLE_PATH)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/pandas/core/generic.py", line 3085, in to_pickle
    to_pickle(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/pandas/io/pickle.py", line 105, in to_pickle
    with get_handle(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/Users/yueyaoz/Downloads/IS3107-FinSum/airflow/ollama-dir'
[2025-04-19T11:35:34.079+0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-19T11:35:34.079+0800] {logging_mixin.py:190} INFO - Task start:2025-04-19 03:35:32.401098+00:00 end:2025-04-19 03:35:34.079010+00:00 duration:1.677912
[2025-04-19T11:35:34.080+0800] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): fetch_yesterday_data> dag:<DAG: reddit_yf_scraper> dagrun:<DagRun reddit_yf_scraper @ 2025-04-19 03:28:54.867003+00:00: manual__2025-04-19T03:28:54.867003+00:00, state:running, queued_at: 2025-04-19 03:28:54.873189+00:00. externally triggered: True>
[2025-04-19T11:35:34.080+0800] {logging_mixin.py:190} INFO - Failure caused by Cannot save file into a non-existent directory: '/Users/yueyaoz/Downloads/IS3107-FinSum/airflow/ollama-dir'
[2025-04-19T11:35:34.081+0800] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=reddit_yf_scraper, task_id=fetch_yesterday_data, run_id=manual__2025-04-19T03:28:54.867003+00:00, execution_date=20250419T032854, start_date=20250419T033532, end_date=20250419T033534
[2025-04-19T11:35:34.093+0800] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-19T11:35:34.093+0800] {standard_task_runner.py:124} ERROR - Failed to execute job 680 for task fetch_yesterday_data (Cannot save file into a non-existent directory: '/Users/yueyaoz/Downloads/IS3107-FinSum/airflow/ollama-dir'; 15334)
Traceback (most recent call last):
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/airflow/dags/dag.py", line 425, in fetch_yesterday_data
    df.to_pickle(PICKLE_PATH)
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/pandas/core/generic.py", line 3085, in to_pickle
    to_pickle(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/pandas/io/pickle.py", line 105, in to_pickle
    with get_handle(
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/Users/yueyaoz/Downloads/IS3107-FinSum/.airflow/lib/python3.10/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/Users/yueyaoz/Downloads/IS3107-FinSum/airflow/ollama-dir'
[2025-04-19T11:35:34.117+0800] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-19T11:35:34.127+0800] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-19T11:35:34.127+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
