[2025-03-21T21:35:34.608+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T21:35:34.614+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_yf_scraper.run_reddit manual__2025-03-21T13:29:22.010242+00:00 [queued]>
[2025-03-21T21:35:34.616+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_yf_scraper.run_reddit manual__2025-03-21T13:29:22.010242+00:00 [queued]>
[2025-03-21T21:35:34.616+0800] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-21T21:35:34.620+0800] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): run_reddit> on 2025-03-21 13:29:22.010242+00:00
[2025-03-21T21:35:34.622+0800] {standard_task_runner.py:72} INFO - Started process 51619 to run task
[2025-03-21T21:35:34.625+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_yf_scraper', 'run_reddit', 'manual__2025-03-21T13:29:22.010242+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/var/folders/xg/h9xj0trn3dxds251bj2q6hf80000gn/T/tmp862ngesv']
[2025-03-21T21:35:34.626+0800] {standard_task_runner.py:105} INFO - Job 45: Subtask run_reddit
[2025-03-21T21:35:34.643+0800] {task_command.py:467} INFO - Running <TaskInstance: reddit_yf_scraper.run_reddit manual__2025-03-21T13:29:22.010242+00:00 [running]> on host ervins-air-2
[2025-03-21T21:35:34.662+0800] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='reddit_yf_scraper' AIRFLOW_CTX_TASK_ID='run_reddit' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T13:29:22.010242+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T13:29:22.010242+00:00'
[2025-03-21T21:35:34.662+0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-21T21:35:34.662+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-21T21:35:34.662+0800] {logging_mixin.py:190} INFO - Current task name:run_reddit state:running start_date:2025-03-21 13:35:34.614717+00:00
[2025-03-21T21:35:34.662+0800] {logging_mixin.py:190} INFO - Dag name:reddit_yf_scraper and current dag run status:running
[2025-03-21T21:35:34.663+0800] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T21:35:35.448+0800] {patcher.py:346} INFO - patching driver executable /Users/ervinyeoh/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2025-03-21T21:35:38.960+0800] {logging_mixin.py:190} INFO - üîç Searching Reddit for AAPL...
[2025-03-21T21:35:44.934+0800] {logging_mixin.py:190} INFO - ‚úÖ Clicked on post 1 for AAPL successfully!
[2025-03-21T21:35:48.690+0800] {logging_mixin.py:190} INFO - üîô Navigated back to search results!
[2025-03-21T21:35:51.517+0800] {logging_mixin.py:190} INFO - ‚úÖ Clicked on post 2 for AAPL successfully!
[2025-03-21T21:35:55.359+0800] {logging_mixin.py:190} INFO - üîô Navigated back to search results!
[2025-03-21T21:35:57.392+0800] {logging_mixin.py:190} INFO - ‚úÖ All posts for AAPL have been processed.
[2025-03-21T21:35:57.427+0800] {logging_mixin.py:190} INFO - üìÅ Saved: /Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/snp500-reddit/AAPL_reddit_last24hours.csv
[2025-03-21T21:35:57.427+0800] {logging_mixin.py:190} INFO - üîç Searching Reddit for NVDA...
[2025-03-21T21:36:01.664+0800] {logging_mixin.py:190} INFO - ‚ùå Error clicking post 1 for NVDA: Message: invalid session id: session deleted as the browser has closed the connection
from disconnected: not connected to DevTools
  (Session info: chrome=134.0.6998.118)
Stacktrace:
0   undetected_chromedriver             0x000000010316e818 undetected_chromedriver + 6105112
1   undetected_chromedriver             0x000000010316641a undetected_chromedriver + 6071322
2   undetected_chromedriver             0x0000000102c01600 undetected_chromedriver + 415232
3   undetected_chromedriver             0x0000000102be715d undetected_chromedriver + 307549
4   undetected_chromedriver             0x0000000102c101ad undetected_chromedriver + 475565
5   undetected_chromedriver             0x0000000102c81d89 undetected_chromedriver + 941449
6   undetected_chromedriver             0x0000000102ca05d5 undetected_chromedriver + 1066453
7   undetected_chromedriver             0x0000000102c793e3 undetected_chromedriver + 906211
8   undetected_chromedriver             0x0000000102c4529a undetected_chromedriver + 692890
9   undetected_chromedriver             0x0000000102c463f1 undetected_chromedriver + 697329
10  undetected_chromedriver             0x000000010312dd10 undetected_chromedriver + 5840144
11  undetected_chromedriver             0x0000000103131be4 undetected_chromedriver + 5856228
12  undetected_chromedriver             0x0000000103108946 undetected_chromedriver + 5687622
13  undetected_chromedriver             0x00000001031325db undetected_chromedriver + 5858779
14  undetected_chromedriver             0x00000001030f7034 undetected_chromedriver + 5615668
15  undetected_chromedriver             0x0000000103154378 undetected_chromedriver + 5997432
16  undetected_chromedriver             0x000000010315453f undetected_chromedriver + 5997887
17  undetected_chromedriver             0x0000000103165ff8 undetected_chromedriver + 6070264
18  libsystem_pthread.dylib             0x00007ff80802d259 _pthread_start + 125
19  libsystem_pthread.dylib             0x00007ff808028c7b thread_start + 15
[2025-03-21T21:36:01.667+0800] {logging_mixin.py:190} INFO - üîç Searching Reddit for MSFT...
[2025-03-21T21:36:01.683+0800] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/dag.py", line 45, in run_reddit
    run_reddit_scraper(tickers)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/reddit_scraper.py", line 21, in run_reddit_scraper
    driver.get(search_url)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 665, in get
    return super().get(url)
           ^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 454, in get
    self.execute(Command.GET, {"url": url})
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
0   undetected_chromedriver             0x000000010316e818 undetected_chromedriver + 6105112
1   undetected_chromedriver             0x000000010316641a undetected_chromedriver + 6071322
2   undetected_chromedriver             0x0000000102c01443 undetected_chromedriver + 414787
3   undetected_chromedriver             0x0000000102c4458f undetected_chromedriver + 689551
4   undetected_chromedriver             0x0000000102c79516 undetected_chromedriver + 906518
5   undetected_chromedriver             0x0000000102c73f1a undetected_chromedriver + 884506
6   undetected_chromedriver             0x0000000102c73087 undetected_chromedriver + 880775
7   undetected_chromedriver             0x0000000102bca2ff undetected_chromedriver + 189183
8   undetected_chromedriver             0x000000010312dd10 undetected_chromedriver + 5840144
9   undetected_chromedriver             0x0000000103131be4 undetected_chromedriver + 5856228
10  undetected_chromedriver             0x0000000103108946 undetected_chromedriver + 5687622
11  undetected_chromedriver             0x00000001031325db undetected_chromedriver + 5858779
12  undetected_chromedriver             0x00000001030f7034 undetected_chromedriver + 5615668
13  undetected_chromedriver             0x0000000102bc8bff undetected_chromedriver + 183295
14  dyld                                0x0000000203c8f310 start + 2432

[2025-03-21T21:36:01.718+0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-21T21:36:01.719+0800] {logging_mixin.py:190} INFO - Task start:2025-03-21 13:35:34.614717+00:00 end:2025-03-21 13:36:01.715251+00:00 duration:27.100534
[2025-03-21T21:36:01.720+0800] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): run_reddit> dag:<DAG: reddit_yf_scraper> dagrun:<DagRun reddit_yf_scraper @ 2025-03-21 13:29:22.010242+00:00: manual__2025-03-21T13:29:22.010242+00:00, state:running, queued_at: 2025-03-21 13:29:22.029009+00:00. externally triggered: True>
[2025-03-21T21:36:01.720+0800] {logging_mixin.py:190} INFO - Failure caused by Message: invalid session id
Stacktrace:
0   undetected_chromedriver             0x000000010316e818 undetected_chromedriver + 6105112
1   undetected_chromedriver             0x000000010316641a undetected_chromedriver + 6071322
2   undetected_chromedriver             0x0000000102c01443 undetected_chromedriver + 414787
3   undetected_chromedriver             0x0000000102c4458f undetected_chromedriver + 689551
4   undetected_chromedriver             0x0000000102c79516 undetected_chromedriver + 906518
5   undetected_chromedriver             0x0000000102c73f1a undetected_chromedriver + 884506
6   undetected_chromedriver             0x0000000102c73087 undetected_chromedriver + 880775
7   undetected_chromedriver             0x0000000102bca2ff undetected_chromedriver + 189183
8   undetected_chromedriver             0x000000010312dd10 undetected_chromedriver + 5840144
9   undetected_chromedriver             0x0000000103131be4 undetected_chromedriver + 5856228
10  undetected_chromedriver             0x0000000103108946 undetected_chromedriver + 5687622
11  undetected_chromedriver             0x00000001031325db undetected_chromedriver + 5858779
12  undetected_chromedriver             0x00000001030f7034 undetected_chromedriver + 5615668
13  undetected_chromedriver             0x0000000102bc8bff undetected_chromedriver + 183295
14  dyld                                0x0000000203c8f310 start + 2432
[2025-03-21T21:36:01.721+0800] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=reddit_yf_scraper, task_id=run_reddit, run_id=manual__2025-03-21T13:29:22.010242+00:00, execution_date=20250321T132922, start_date=20250321T133534, end_date=20250321T133601
[2025-03-21T21:36:01.734+0800] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T21:36:01.735+0800] {standard_task_runner.py:124} ERROR - Failed to execute job 45 for task run_reddit (Message: invalid session id
Stacktrace:
0   undetected_chromedriver             0x000000010316e818 undetected_chromedriver + 6105112
1   undetected_chromedriver             0x000000010316641a undetected_chromedriver + 6071322
2   undetected_chromedriver             0x0000000102c01443 undetected_chromedriver + 414787
3   undetected_chromedriver             0x0000000102c4458f undetected_chromedriver + 689551
4   undetected_chromedriver             0x0000000102c79516 undetected_chromedriver + 906518
5   undetected_chromedriver             0x0000000102c73f1a undetected_chromedriver + 884506
6   undetected_chromedriver             0x0000000102c73087 undetected_chromedriver + 880775
7   undetected_chromedriver             0x0000000102bca2ff undetected_chromedriver + 189183
8   undetected_chromedriver             0x000000010312dd10 undetected_chromedriver + 5840144
9   undetected_chromedriver             0x0000000103131be4 undetected_chromedriver + 5856228
10  undetected_chromedriver             0x0000000103108946 undetected_chromedriver + 5687622
11  undetected_chromedriver             0x00000001031325db undetected_chromedriver + 5858779
12  undetected_chromedriver             0x00000001030f7034 undetected_chromedriver + 5615668
13  undetected_chromedriver             0x0000000102bc8bff undetected_chromedriver + 183295
14  dyld                                0x0000000203c8f310 start + 2432
; 51619)
Traceback (most recent call last):
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/dag.py", line 45, in run_reddit
    run_reddit_scraper(tickers)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/reddit_scraper.py", line 21, in run_reddit_scraper
    driver.get(search_url)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 665, in get
    return super().get(url)
           ^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 454, in get
    self.execute(Command.GET, {"url": url})
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
0   undetected_chromedriver             0x000000010316e818 undetected_chromedriver + 6105112
1   undetected_chromedriver             0x000000010316641a undetected_chromedriver + 6071322
2   undetected_chromedriver             0x0000000102c01443 undetected_chromedriver + 414787
3   undetected_chromedriver             0x0000000102c4458f undetected_chromedriver + 689551
4   undetected_chromedriver             0x0000000102c79516 undetected_chromedriver + 906518
5   undetected_chromedriver             0x0000000102c73f1a undetected_chromedriver + 884506
6   undetected_chromedriver             0x0000000102c73087 undetected_chromedriver + 880775
7   undetected_chromedriver             0x0000000102bca2ff undetected_chromedriver + 189183
8   undetected_chromedriver             0x000000010312dd10 undetected_chromedriver + 5840144
9   undetected_chromedriver             0x0000000103131be4 undetected_chromedriver + 5856228
10  undetected_chromedriver             0x0000000103108946 undetected_chromedriver + 5687622
11  undetected_chromedriver             0x00000001031325db undetected_chromedriver + 5858779
12  undetected_chromedriver             0x00000001030f7034 undetected_chromedriver + 5615668
13  undetected_chromedriver             0x0000000102bc8bff undetected_chromedriver + 183295
14  dyld                                0x0000000203c8f310 start + 2432

[2025-03-21T21:36:01.759+0800] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-21T21:36:01.773+0800] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-21T21:36:01.775+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
