[2025-04-02T11:44:39.144+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-02T11:44:39.155+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_yf_scraper.run_reddit manual__2025-04-02T03:37:24.461652+00:00 [queued]>
[2025-04-02T11:44:39.160+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_yf_scraper.run_reddit manual__2025-04-02T03:37:24.461652+00:00 [queued]>
[2025-04-02T11:44:39.161+0800] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-04-02T11:44:39.171+0800] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): run_reddit> on 2025-04-02 03:37:24.461652+00:00
[2025-04-02T11:44:39.173+0800] {standard_task_runner.py:72} INFO - Started process 21803 to run task
[2025-04-02T11:44:39.178+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_yf_scraper', 'run_reddit', 'manual__2025-04-02T03:37:24.461652+00:00', '--job-id', '181', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/var/folders/xg/h9xj0trn3dxds251bj2q6hf80000gn/T/tmpfq0rbruc']
[2025-04-02T11:44:39.181+0800] {standard_task_runner.py:105} INFO - Job 181: Subtask run_reddit
[2025-04-02T11:44:39.220+0800] {task_command.py:467} INFO - Running <TaskInstance: reddit_yf_scraper.run_reddit manual__2025-04-02T03:37:24.461652+00:00 [running]> on host ervins-macbook-air-2.local
[2025-04-02T11:44:39.258+0800] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='reddit_yf_scraper' AIRFLOW_CTX_TASK_ID='run_reddit' AIRFLOW_CTX_EXECUTION_DATE='2025-04-02T03:37:24.461652+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-02T03:37:24.461652+00:00'
[2025-04-02T11:44:39.259+0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-02T11:44:39.260+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-02T11:44:39.260+0800] {logging_mixin.py:190} INFO - Current task name:run_reddit state:running start_date:2025-04-02 03:44:39.155467+00:00
[2025-04-02T11:44:39.260+0800] {logging_mixin.py:190} INFO - Dag name:reddit_yf_scraper and current dag run status:running
[2025-04-02T11:44:39.260+0800] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-02T11:44:39.838+0800] {patcher.py:346} INFO - patching driver executable /Users/ervinyeoh/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2025-04-02T11:44:44.481+0800] {logging_mixin.py:190} INFO - üîç Searching Reddit for AAPL...
[2025-04-02T11:44:50.040+0800] {logging_mixin.py:190} INFO - ‚úÖ All posts for AAPL have been processed.
[2025-04-02T11:44:50.042+0800] {logging_mixin.py:190} INFO - üîç Searching Reddit for NVDA...
[2025-04-02T11:44:55.116+0800] {logging_mixin.py:190} INFO - ‚úÖ Clicked on post 1 for NVDA successfully!
[2025-04-02T11:44:58.839+0800] {logging_mixin.py:190} INFO - üîô Navigated back to search results!
[2025-04-02T11:45:00.848+0800] {logging_mixin.py:190} INFO - ‚úÖ All posts for NVDA have been processed.
[2025-04-02T11:45:00.865+0800] {logging_mixin.py:190} INFO - üìÅ Saved: /Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/snp500-reddit-test/NVDA_reddit_20250402.csv
[2025-04-02T11:45:00.866+0800] {logging_mixin.py:190} INFO - üîç Searching Reddit for MSFT...
[2025-04-02T11:45:00.868+0800] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/dag.py", line 54, in run_reddit
    run_reddit_scraper(tickers)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/reddit_scraper.py", line 31, in run_reddit_scraper
    driver.get(search_url)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 665, in get
    return super().get(url)
           ^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 454, in get
    self.execute(Command.GET, {"url": url})
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=135.0.7049.42)
Stacktrace:
0   undetected_chromedriver             0x00000001015a4568 undetected_chromedriver + 6088040
1   undetected_chromedriver             0x000000010159c17a undetected_chromedriver + 6054266
2   undetected_chromedriver             0x000000010103b540 undetected_chromedriver + 415040
3   undetected_chromedriver             0x000000010100f605 undetected_chromedriver + 235013
4   undetected_chromedriver             0x00000001010bb9ae undetected_chromedriver + 940462
5   undetected_chromedriver             0x00000001010da3ac undetected_chromedriver + 1065900
6   undetected_chromedriver             0x00000001010b31c3 undetected_chromedriver + 905667
7   undetected_chromedriver             0x000000010107f05a undetected_chromedriver + 692314
8   undetected_chromedriver             0x00000001010801b1 undetected_chromedriver + 696753
9   undetected_chromedriver             0x0000000101563c90 undetected_chromedriver + 5823632
10  undetected_chromedriver             0x0000000101567b44 undetected_chromedriver + 5839684
11  undetected_chromedriver             0x000000010153ee86 undetected_chromedriver + 5672582
12  undetected_chromedriver             0x000000010156853b undetected_chromedriver + 5842235
13  undetected_chromedriver             0x000000010152d824 undetected_chromedriver + 5601316
14  undetected_chromedriver             0x000000010158a618 undetected_chromedriver + 5981720
15  undetected_chromedriver             0x000000010158a7df undetected_chromedriver + 5982175
16  undetected_chromedriver             0x000000010159bd58 undetected_chromedriver + 6053208
17  libsystem_pthread.dylib             0x00007ff8090b1259 _pthread_start + 125
18  libsystem_pthread.dylib             0x00007ff8090acc7b thread_start + 15

[2025-04-02T11:45:00.881+0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-02T11:45:00.882+0800] {logging_mixin.py:190} INFO - Task start:2025-04-02 03:44:39.155467+00:00 end:2025-04-02 03:45:00.881152+00:00 duration:21.725685
[2025-04-02T11:45:00.882+0800] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): run_reddit> dag:<DAG: reddit_yf_scraper> dagrun:<DagRun reddit_yf_scraper @ 2025-04-02 03:37:24.461652+00:00: manual__2025-04-02T03:37:24.461652+00:00, state:running, queued_at: 2025-04-02 03:37:24.471720+00:00. externally triggered: True>
[2025-04-02T11:45:00.882+0800] {logging_mixin.py:190} INFO - Failure caused by Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=135.0.7049.42)
Stacktrace:
0   undetected_chromedriver             0x00000001015a4568 undetected_chromedriver + 6088040
1   undetected_chromedriver             0x000000010159c17a undetected_chromedriver + 6054266
2   undetected_chromedriver             0x000000010103b540 undetected_chromedriver + 415040
3   undetected_chromedriver             0x000000010100f605 undetected_chromedriver + 235013
4   undetected_chromedriver             0x00000001010bb9ae undetected_chromedriver + 940462
5   undetected_chromedriver             0x00000001010da3ac undetected_chromedriver + 1065900
6   undetected_chromedriver             0x00000001010b31c3 undetected_chromedriver + 905667
7   undetected_chromedriver             0x000000010107f05a undetected_chromedriver + 692314
8   undetected_chromedriver             0x00000001010801b1 undetected_chromedriver + 696753
9   undetected_chromedriver             0x0000000101563c90 undetected_chromedriver + 5823632
10  undetected_chromedriver             0x0000000101567b44 undetected_chromedriver + 5839684
11  undetected_chromedriver             0x000000010153ee86 undetected_chromedriver + 5672582
12  undetected_chromedriver             0x000000010156853b undetected_chromedriver + 5842235
13  undetected_chromedriver             0x000000010152d824 undetected_chromedriver + 5601316
14  undetected_chromedriver             0x000000010158a618 undetected_chromedriver + 5981720
15  undetected_chromedriver             0x000000010158a7df undetected_chromedriver + 5982175
16  undetected_chromedriver             0x000000010159bd58 undetected_chromedriver + 6053208
17  libsystem_pthread.dylib             0x00007ff8090b1259 _pthread_start + 125
18  libsystem_pthread.dylib             0x00007ff8090acc7b thread_start + 15
[2025-04-02T11:45:00.883+0800] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=reddit_yf_scraper, task_id=run_reddit, run_id=manual__2025-04-02T03:37:24.461652+00:00, execution_date=20250402T033724, start_date=20250402T034439, end_date=20250402T034500
[2025-04-02T11:45:00.893+0800] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-02T11:45:00.893+0800] {standard_task_runner.py:124} ERROR - Failed to execute job 181 for task run_reddit (Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=135.0.7049.42)
Stacktrace:
0   undetected_chromedriver             0x00000001015a4568 undetected_chromedriver + 6088040
1   undetected_chromedriver             0x000000010159c17a undetected_chromedriver + 6054266
2   undetected_chromedriver             0x000000010103b540 undetected_chromedriver + 415040
3   undetected_chromedriver             0x000000010100f605 undetected_chromedriver + 235013
4   undetected_chromedriver             0x00000001010bb9ae undetected_chromedriver + 940462
5   undetected_chromedriver             0x00000001010da3ac undetected_chromedriver + 1065900
6   undetected_chromedriver             0x00000001010b31c3 undetected_chromedriver + 905667
7   undetected_chromedriver             0x000000010107f05a undetected_chromedriver + 692314
8   undetected_chromedriver             0x00000001010801b1 undetected_chromedriver + 696753
9   undetected_chromedriver             0x0000000101563c90 undetected_chromedriver + 5823632
10  undetected_chromedriver             0x0000000101567b44 undetected_chromedriver + 5839684
11  undetected_chromedriver             0x000000010153ee86 undetected_chromedriver + 5672582
12  undetected_chromedriver             0x000000010156853b undetected_chromedriver + 5842235
13  undetected_chromedriver             0x000000010152d824 undetected_chromedriver + 5601316
14  undetected_chromedriver             0x000000010158a618 undetected_chromedriver + 5981720
15  undetected_chromedriver             0x000000010158a7df undetected_chromedriver + 5982175
16  undetected_chromedriver             0x000000010159bd58 undetected_chromedriver + 6053208
17  libsystem_pthread.dylib             0x00007ff8090b1259 _pthread_start + 125
18  libsystem_pthread.dylib             0x00007ff8090acc7b thread_start + 15
; 21803)
Traceback (most recent call last):
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/dag.py", line 54, in run_reddit
    run_reddit_scraper(tickers)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/reddit_scraper.py", line 31, in run_reddit_scraper
    driver.get(search_url)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 665, in get
    return super().get(url)
           ^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 454, in get
    self.execute(Command.GET, {"url": url})
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=135.0.7049.42)
Stacktrace:
0   undetected_chromedriver             0x00000001015a4568 undetected_chromedriver + 6088040
1   undetected_chromedriver             0x000000010159c17a undetected_chromedriver + 6054266
2   undetected_chromedriver             0x000000010103b540 undetected_chromedriver + 415040
3   undetected_chromedriver             0x000000010100f605 undetected_chromedriver + 235013
4   undetected_chromedriver             0x00000001010bb9ae undetected_chromedriver + 940462
5   undetected_chromedriver             0x00000001010da3ac undetected_chromedriver + 1065900
6   undetected_chromedriver             0x00000001010b31c3 undetected_chromedriver + 905667
7   undetected_chromedriver             0x000000010107f05a undetected_chromedriver + 692314
8   undetected_chromedriver             0x00000001010801b1 undetected_chromedriver + 696753
9   undetected_chromedriver             0x0000000101563c90 undetected_chromedriver + 5823632
10  undetected_chromedriver             0x0000000101567b44 undetected_chromedriver + 5839684
11  undetected_chromedriver             0x000000010153ee86 undetected_chromedriver + 5672582
12  undetected_chromedriver             0x000000010156853b undetected_chromedriver + 5842235
13  undetected_chromedriver             0x000000010152d824 undetected_chromedriver + 5601316
14  undetected_chromedriver             0x000000010158a618 undetected_chromedriver + 5981720
15  undetected_chromedriver             0x000000010158a7df undetected_chromedriver + 5982175
16  undetected_chromedriver             0x000000010159bd58 undetected_chromedriver + 6053208
17  libsystem_pthread.dylib             0x00007ff8090b1259 _pthread_start + 125
18  libsystem_pthread.dylib             0x00007ff8090acc7b thread_start + 15

[2025-04-02T11:45:00.914+0800] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-02T11:45:00.929+0800] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-02T11:45:00.931+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
