[2025-03-21T21:41:20.624+0800] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T21:41:20.630+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reddit_yf_scraper.run_reddit manual__2025-03-21T13:36:17.273267+00:00 [queued]>
[2025-03-21T21:41:20.633+0800] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reddit_yf_scraper.run_reddit manual__2025-03-21T13:36:17.273267+00:00 [queued]>
[2025-03-21T21:41:20.633+0800] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-21T21:41:20.637+0800] {taskinstance.py:2890} INFO - Executing <Task(_PythonDecoratedOperator): run_reddit> on 2025-03-21 13:36:17.273267+00:00
[2025-03-21T21:41:20.638+0800] {standard_task_runner.py:72} INFO - Started process 52311 to run task
[2025-03-21T21:41:20.641+0800] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'reddit_yf_scraper', 'run_reddit', 'manual__2025-03-21T13:36:17.273267+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/var/folders/xg/h9xj0trn3dxds251bj2q6hf80000gn/T/tmpki28vv0z']
[2025-03-21T21:41:20.642+0800] {standard_task_runner.py:105} INFO - Job 63: Subtask run_reddit
[2025-03-21T21:41:20.669+0800] {task_command.py:467} INFO - Running <TaskInstance: reddit_yf_scraper.run_reddit manual__2025-03-21T13:36:17.273267+00:00 [running]> on host ervins-air-2
[2025-03-21T21:41:20.690+0800] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='reddit_yf_scraper' AIRFLOW_CTX_TASK_ID='run_reddit' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T13:36:17.273267+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T13:36:17.273267+00:00'
[2025-03-21T21:41:20.691+0800] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-21T21:41:20.693+0800] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-21T21:41:20.693+0800] {logging_mixin.py:190} INFO - Current task name:run_reddit state:running start_date:2025-03-21 13:41:20.631120+00:00
[2025-03-21T21:41:20.694+0800] {logging_mixin.py:190} INFO - Dag name:reddit_yf_scraper and current dag run status:running
[2025-03-21T21:41:20.694+0800] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T21:41:21.346+0800] {patcher.py:346} INFO - patching driver executable /Users/ervinyeoh/Library/Application Support/undetected_chromedriver/undetected_chromedriver
[2025-03-21T21:41:24.297+0800] {logging_mixin.py:190} INFO - üîç Searching Reddit for AAPL...
[2025-03-21T21:41:26.772+0800] {logging_mixin.py:190} INFO - ‚ùå Error clicking post 1 for AAPL: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=134.0.6998.118)
Stacktrace:
0   undetected_chromedriver             0x00000001046a4818 undetected_chromedriver + 6105112
1   undetected_chromedriver             0x000000010469c41a undetected_chromedriver + 6071322
2   undetected_chromedriver             0x0000000104137600 undetected_chromedriver + 415232
3   undetected_chromedriver             0x000000010410b675 undetected_chromedriver + 235125
4   undetected_chromedriver             0x00000001041b7bde undetected_chromedriver + 941022
5   undetected_chromedriver             0x00000001041d65d5 undetected_chromedriver + 1066453
6   undetected_chromedriver             0x00000001041af3e3 undetected_chromedriver + 906211
7   undetected_chromedriver             0x000000010417b29a undetected_chromedriver + 692890
8   undetected_chromedriver             0x000000010417c3f1 undetected_chromedriver + 697329
9   undetected_chromedriver             0x0000000104663d10 undetected_chromedriver + 5840144
10  undetected_chromedriver             0x0000000104667be4 undetected_chromedriver + 5856228
11  undetected_chromedriver             0x000000010463e946 undetected_chromedriver + 5687622
12  undetected_chromedriver             0x00000001046685db undetected_chromedriver + 5858779
13  undetected_chromedriver             0x000000010462d034 undetected_chromedriver + 5615668
14  undetected_chromedriver             0x000000010468a378 undetected_chromedriver + 5997432
15  undetected_chromedriver             0x000000010468a53f undetected_chromedriver + 5997887
16  undetected_chromedriver             0x000000010469bff8 undetected_chromedriver + 6070264
17  libsystem_pthread.dylib             0x00007ff80802d259 _pthread_start + 125
18  libsystem_pthread.dylib             0x00007ff808028c7b thread_start + 15
[2025-03-21T21:41:26.773+0800] {logging_mixin.py:190} INFO - üîç Searching Reddit for NVDA...
[2025-03-21T21:41:26.775+0800] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/dag.py", line 45, in run_reddit
    run_reddit_scraper(tickers)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/reddit_scraper.py", line 21, in run_reddit_scraper
    driver.get(search_url)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 665, in get
    return super().get(url)
           ^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 454, in get
    self.execute(Command.GET, {"url": url})
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=134.0.6998.118)
Stacktrace:
0   undetected_chromedriver             0x00000001046a4818 undetected_chromedriver + 6105112
1   undetected_chromedriver             0x000000010469c41a undetected_chromedriver + 6071322
2   undetected_chromedriver             0x0000000104137600 undetected_chromedriver + 415232
3   undetected_chromedriver             0x000000010410b675 undetected_chromedriver + 235125
4   undetected_chromedriver             0x00000001041b7bde undetected_chromedriver + 941022
5   undetected_chromedriver             0x00000001041d65d5 undetected_chromedriver + 1066453
6   undetected_chromedriver             0x00000001041af3e3 undetected_chromedriver + 906211
7   undetected_chromedriver             0x000000010417b29a undetected_chromedriver + 692890
8   undetected_chromedriver             0x000000010417c3f1 undetected_chromedriver + 697329
9   undetected_chromedriver             0x0000000104663d10 undetected_chromedriver + 5840144
10  undetected_chromedriver             0x0000000104667be4 undetected_chromedriver + 5856228
11  undetected_chromedriver             0x000000010463e946 undetected_chromedriver + 5687622
12  undetected_chromedriver             0x00000001046685db undetected_chromedriver + 5858779
13  undetected_chromedriver             0x000000010462d034 undetected_chromedriver + 5615668
14  undetected_chromedriver             0x000000010468a378 undetected_chromedriver + 5997432
15  undetected_chromedriver             0x000000010468a53f undetected_chromedriver + 5997887
16  undetected_chromedriver             0x000000010469bff8 undetected_chromedriver + 6070264
17  libsystem_pthread.dylib             0x00007ff80802d259 _pthread_start + 125
18  libsystem_pthread.dylib             0x00007ff808028c7b thread_start + 15

[2025-03-21T21:41:26.792+0800] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-21T21:41:26.792+0800] {logging_mixin.py:190} INFO - Task start:2025-03-21 13:41:20.631120+00:00 end:2025-03-21 13:41:26.792127+00:00 duration:6.161007
[2025-03-21T21:41:26.793+0800] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): run_reddit> dag:<DAG: reddit_yf_scraper> dagrun:<DagRun reddit_yf_scraper @ 2025-03-21 13:36:17.273267+00:00: manual__2025-03-21T13:36:17.273267+00:00, state:running, queued_at: 2025-03-21 13:36:17.287941+00:00. externally triggered: True>
[2025-03-21T21:41:26.793+0800] {logging_mixin.py:190} INFO - Failure caused by Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=134.0.6998.118)
Stacktrace:
0   undetected_chromedriver             0x00000001046a4818 undetected_chromedriver + 6105112
1   undetected_chromedriver             0x000000010469c41a undetected_chromedriver + 6071322
2   undetected_chromedriver             0x0000000104137600 undetected_chromedriver + 415232
3   undetected_chromedriver             0x000000010410b675 undetected_chromedriver + 235125
4   undetected_chromedriver             0x00000001041b7bde undetected_chromedriver + 941022
5   undetected_chromedriver             0x00000001041d65d5 undetected_chromedriver + 1066453
6   undetected_chromedriver             0x00000001041af3e3 undetected_chromedriver + 906211
7   undetected_chromedriver             0x000000010417b29a undetected_chromedriver + 692890
8   undetected_chromedriver             0x000000010417c3f1 undetected_chromedriver + 697329
9   undetected_chromedriver             0x0000000104663d10 undetected_chromedriver + 5840144
10  undetected_chromedriver             0x0000000104667be4 undetected_chromedriver + 5856228
11  undetected_chromedriver             0x000000010463e946 undetected_chromedriver + 5687622
12  undetected_chromedriver             0x00000001046685db undetected_chromedriver + 5858779
13  undetected_chromedriver             0x000000010462d034 undetected_chromedriver + 5615668
14  undetected_chromedriver             0x000000010468a378 undetected_chromedriver + 5997432
15  undetected_chromedriver             0x000000010468a53f undetected_chromedriver + 5997887
16  undetected_chromedriver             0x000000010469bff8 undetected_chromedriver + 6070264
17  libsystem_pthread.dylib             0x00007ff80802d259 _pthread_start + 125
18  libsystem_pthread.dylib             0x00007ff808028c7b thread_start + 15
[2025-03-21T21:41:26.793+0800] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=reddit_yf_scraper, task_id=run_reddit, run_id=manual__2025-03-21T13:36:17.273267+00:00, execution_date=20250321T133617, start_date=20250321T134120, end_date=20250321T134126
[2025-03-21T21:41:26.803+0800] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T21:41:26.804+0800] {standard_task_runner.py:124} ERROR - Failed to execute job 63 for task run_reddit (Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=134.0.6998.118)
Stacktrace:
0   undetected_chromedriver             0x00000001046a4818 undetected_chromedriver + 6105112
1   undetected_chromedriver             0x000000010469c41a undetected_chromedriver + 6071322
2   undetected_chromedriver             0x0000000104137600 undetected_chromedriver + 415232
3   undetected_chromedriver             0x000000010410b675 undetected_chromedriver + 235125
4   undetected_chromedriver             0x00000001041b7bde undetected_chromedriver + 941022
5   undetected_chromedriver             0x00000001041d65d5 undetected_chromedriver + 1066453
6   undetected_chromedriver             0x00000001041af3e3 undetected_chromedriver + 906211
7   undetected_chromedriver             0x000000010417b29a undetected_chromedriver + 692890
8   undetected_chromedriver             0x000000010417c3f1 undetected_chromedriver + 697329
9   undetected_chromedriver             0x0000000104663d10 undetected_chromedriver + 5840144
10  undetected_chromedriver             0x0000000104667be4 undetected_chromedriver + 5856228
11  undetected_chromedriver             0x000000010463e946 undetected_chromedriver + 5687622
12  undetected_chromedriver             0x00000001046685db undetected_chromedriver + 5858779
13  undetected_chromedriver             0x000000010462d034 undetected_chromedriver + 5615668
14  undetected_chromedriver             0x000000010468a378 undetected_chromedriver + 5997432
15  undetected_chromedriver             0x000000010468a53f undetected_chromedriver + 5997887
16  undetected_chromedriver             0x000000010469bff8 undetected_chromedriver + 6070264
17  libsystem_pthread.dylib             0x00007ff80802d259 _pthread_start + 125
18  libsystem_pthread.dylib             0x00007ff808028c7b thread_start + 15
; 52311)
Traceback (most recent call last):
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/dag.py", line 45, in run_reddit
    run_reddit_scraper(tickers)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/airflow/dags/reddit_scraper.py", line 21, in run_reddit_scraper
    driver.get(search_url)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 665, in get
    return super().get(url)
           ^^^^^^^^^^^^^^^^
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 454, in get
    self.execute(Command.GET, {"url": url})
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 429, in execute
    self.error_handler.check_response(response)
  File "/Users/ervinyeoh/Desktop/unimods/is3107/project/.venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=134.0.6998.118)
Stacktrace:
0   undetected_chromedriver             0x00000001046a4818 undetected_chromedriver + 6105112
1   undetected_chromedriver             0x000000010469c41a undetected_chromedriver + 6071322
2   undetected_chromedriver             0x0000000104137600 undetected_chromedriver + 415232
3   undetected_chromedriver             0x000000010410b675 undetected_chromedriver + 235125
4   undetected_chromedriver             0x00000001041b7bde undetected_chromedriver + 941022
5   undetected_chromedriver             0x00000001041d65d5 undetected_chromedriver + 1066453
6   undetected_chromedriver             0x00000001041af3e3 undetected_chromedriver + 906211
7   undetected_chromedriver             0x000000010417b29a undetected_chromedriver + 692890
8   undetected_chromedriver             0x000000010417c3f1 undetected_chromedriver + 697329
9   undetected_chromedriver             0x0000000104663d10 undetected_chromedriver + 5840144
10  undetected_chromedriver             0x0000000104667be4 undetected_chromedriver + 5856228
11  undetected_chromedriver             0x000000010463e946 undetected_chromedriver + 5687622
12  undetected_chromedriver             0x00000001046685db undetected_chromedriver + 5858779
13  undetected_chromedriver             0x000000010462d034 undetected_chromedriver + 5615668
14  undetected_chromedriver             0x000000010468a378 undetected_chromedriver + 5997432
15  undetected_chromedriver             0x000000010468a53f undetected_chromedriver + 5997887
16  undetected_chromedriver             0x000000010469bff8 undetected_chromedriver + 6070264
17  libsystem_pthread.dylib             0x00007ff80802d259 _pthread_start + 125
18  libsystem_pthread.dylib             0x00007ff808028c7b thread_start + 15

[2025-03-21T21:41:26.853+0800] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-21T21:41:26.865+0800] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-21T21:41:26.866+0800] {local_task_job_runner.py:245} INFO - ::endgroup::
